### ISSUE TITLE
How to reproduce the AMC 2023 results?

### ISSUE THREAD

**Issue by fzyzcjy** [project-numina/aimo-progress-prize#18]
Hi, thanks for the open sourced project! I wonder how to reproduce the AMC 2023 results? Currently I have tried:

* start with the https://github.com/project-numina/aimo-progress-prize/blob/main/kaggle-solution.ipynb
* change number of attempts from 48 to 64
* change GPTQ to non-quantized model
* change the dataset to the 40 problems with name AMC 2023 in AI-MO/aimo-validation-amc dataset

However, the result is 25/40 instead of 31/40. Thus, I would appreciate it if I could know what hyperparameters etc are used to reproduce the results.

**Comment by liyongsea** [comment]
We have not try the non-quantized model. Let me double check to see if we can reproduce the problem

**Comment by fzyzcjy** [comment]
@liyongsea Thank you and looking forward to the results! I am happy to do other experiments if you need (just ping me).

**Comment by fzyzcjy** [comment]
Btw I can get 27~28 of 40 after removing the code to limit the answer within 0-999 (since two questions have answer >1000). But still has not reach 31/40 yet.

**Comment by fzyzcjy** [comment]
Run with gptq quantized model again and find 30/40 now (though not 31/40 but looks close enough). Sorry for bothering, and thanks again for the great project!
